# Generated by Django 4.2.8 on 2023-12-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='car_image/')),
                ('year_of_issue', models.IntegerField(verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('body', models.CharField(choices=[('Sedan', 'Седан'), ('Hatchback 5dor.', 'Хэтчбек 5дв.'), ('SUV 5dor.', 'Внедорожник 5дв.'), ('Universal', 'Универсал'), ('Coupe', 'Купе'), ('Minivan', 'Минивэн'), ('Cabriolet', 'Кабриолет')], max_length=50, verbose_name='Кузов')),
                ('color', models.CharField(choices=[('White', 'Белый'), ('Black', 'Черный'), ('Red', 'Красный'), ('Yellow', 'Желтый'), ('Orange', 'Оранжевый'), ('Green', 'Зеленый'), ('Blue', 'Синий'), ('Purple', 'Фиолетовый'), ('Pink', 'Розовый'), ('Brown', 'Коричневый'), ('Grey', 'Серый')], max_length=50, verbose_name='Цвет')),
                ('engine', models.CharField(choices=[('Benzine', 'Бензин'), ('Diesel', 'Дизель'), ('Hybrid', 'Гибрид'), ('Electro', 'Электро'), ('Turbocharged', 'Турбированный'), ('Atmospheric', 'Атмосферный')], max_length=50, verbose_name='Двигатель')),
                ('transmission', models.CharField(choices=[('Automatic', 'Автоматическая'), ('Mechanical', 'Механика'), ('Variator', 'Вариатор'), ('Robot', 'Робот')], max_length=50, verbose_name='Коробка передач')),
                ('drive_unit', models.CharField(choices=[('FWD', 'Передний'), ('RWD', 'Задний'), ('AWD', 'Полный')], max_length=50, verbose_name='Привод')),
                ('rudder', models.CharField(choices=[('Right', 'Правый'), ('Left', 'Левый')], max_length=50, verbose_name='Руль')),
                ('car_condition', models.CharField(blank=True, max_length=100, verbose_name='Состояние')),
                ('customs', models.CharField(choices=[('Customs_cleared', 'Растоможен'), ('Not_Cleared_by_Customs', 'Не Растоможен')], max_length=50, verbose_name='Таможня')),
                ('other', models.CharField(blank=True, max_length=400, verbose_name='Прочее')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
